### ISSUE TITLE
Calculate correct staking balance when snapshot index = 15

### ISSUE THREAD

**Issue by utdrmac** [tezos-reward-distributor-organization/tezos-reward-distributor#239]
RE: https://medium.com/@_MisterWalker_/we-all-were-wrong-baking-bad-and-most-bakers-were-using-wrong-data-to-calculate-staking-rewards-a8c26f5ec62b

```
just to clarify the logic:
  - when snapshotIndex < 15, realStakingBalance = staking_balance
  - when snapshotIndex == 15, realStakingBalance = (staking_balance - metadataUnfrozenRewards)
```

**Comment by dansan566** [comment]
This issue is only solved with argument "--reward_data_provider=tzkt"?

**Comment by utdrmac** [comment]
The issue is otherwise only resolved when using the new tzkt provider, yes. If using rpc, the issue is resolved using the linked PR. If using tzstats, issue remains as this will/should be the responsibility for tzstats to fix.

**Comment by jdsika** [comment]
tzstats fixed this mid July with API Version v006-2020-06-24

[release notes](https://tzstats.com/docs/api/index.html#2020-06-24)

Relevant from changelog:
- etl/income: don’t count unfrozen rewards into end-of-cycle snapshots
- etl/income: fixed total_income to include all fees and denunciation rewards
